name: CI for PRs

on:
  pull_request:
    types: [ opened, ready_for_review ]

jobs:
  add-auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assigns default PR metadata
        uses: devmyong/auto-assign@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run tests
        run: |
          go test ./...  # 프로젝트 내 모든 테스트 실행

  show-event:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Display GITHUB_EVENT_PATH content
        run: cat "$GITHUB_EVENT_PATH"