name: D day labeler

on:
  workflow_dispatch:

env:
  GO_VERSION: 1.23

jobs:
  decrement-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run d-day-labeler Action
        uses: devmyong/d-day-labeler@v1.0.1
