name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
#    paths:
#      - 'services/todo/**'
#      - 'services/user/**'

jobs:
  versioning-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set Git user info
        run: |
          git config --global user.email "myong.dev@gmail.com"
          git config --global user.name "damon"

      - name: Update remote URL with GITHUB_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DevMyong/todo.git

      - name: Increment version based on commit type
        run: |
          VERSION=$(cat version.txt)
          IFS='.' read -r major minor patch <<< "$VERSION"
          
          # 커밋 메시지에 따라 버전 증가
          if git log -1 --pretty=%B | grep -q "BREAKING CHANGE"; then
            major=$((major + 1))
            minor=0
            patch=0
          elif git log -1 --pretty=%B | grep -q "feat"; then
            minor=$((minor + 1))
            patch=0
          elif git log -1 --pretty=%B | grep -q "fix"; then
            patch=$((patch + 1))
          fi

          new_version="$major.$minor.$patch"
          echo $new_version > version.txt
          git commit -am "Bump version to $new_version"
          git tag -a "v$new_version" -m "Release version $new_version"
          git push origin --tags

      - name: Build Docker image
        run: |
          VERSION=$(cat version.txt)
          docker build -t my-app:$VERSION .
